# Generated by Django 2.0 on 2018-09-05 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 18, 52, 52, 467562, tzinfo=utc)),
        ),
    ]
