# Generated by Django 2.0 on 2019-04-11 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190411_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 17, 47, 18, 737371, tzinfo=utc)),
        ),
    ]
