# Generated by Django 2.0 on 2019-04-12 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190412_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 12, 11, 55, 24, 84250, tzinfo=utc)),
        ),
    ]
